[features]
seeds = false

[programs.localnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"

[programs.devnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"

[programs.mainnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./auth.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
[[test.validator.clone]]
address = "DsRmdpRZJwagptu4MMN7GJWaPuwPgStWPUSbfAinYCg9"
[[test.validator.clone]]
address = "DbmHBMDepTnKyTnSccvji5FJv8tDGjEoo6ivV2qR4tY2"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/modify.ts -g 'beeen'"
