[features]
seeds = false

[programs.localnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"
bake_sale = "bakeCUvhUFBvQwzsuAHjuzjoXdnHeA4yD4rtjuBzMoV"

[programs.devnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"
bake_sale = "bakeCUvhUFBvQwzsuAHjuzjoXdnHeA4yD4rtjuBzMoV"

[programs.mainnet]
cupcake = "cakeGJxEdGpZ3MJP8sM3QypwzuzZpko1ueonUQgKLPE"
bake_sale = "bakeCUvhUFBvQwzsuAHjuzjoXdnHeA4yD4rtjuBzMoV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
